name: PoC Deploy Trigger
on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Entorno de destino'
        required: true
        default: 'sandbox'
        type: choice
        options: [sandbox, homologacion]

jobs:
  simulate-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ConfirmaciÃ³n de recepciÃ³n
        run: |
          echo "ðŸš€ Desplegando en el entorno: ${{ github.event.inputs.target_env }}"
          sleep 5
          echo "âœ… Despliegue completado con Ã©xito."